version: '3'

services:
  maildev:
    image: djfarrelly/maildev
    command:
      - bin/maildev
      - --web=80
      - --smtp=25
      - --hide-extensions STARTTLS
    ports:
      - "25:25"
      - 8081:80
